Cordoplug 430
Onegini/cordova-plugin-onegini pull request #197
Opened 2020-12-07 13:59 UTC by marcin-waligorski-onegini

2020-12-08 10:11 UTC, mhwildeman requested changes

2020-12-08 10:11 UTC, mhwildeman commented on hooks/resolve_dependencies.js
> +  stripSimulatorArchitecture: 'ONEGINI_STRIP_SIMULATOR_ARCHITECTURE',
Since we're building this mainly for Outsystems, `stripSimulatorArchitecture` must not only be populated through ENV_VARS, but also from artifactory.properties (or some other .properties file)

2020-12-08 10:22 UTC, mhwildeman requested changes

2020-12-08 10:22 UTC, mhwildeman commented on hooks/resolve_dependencies.js
> +  stripSimulatorArchitecture: 'ONEGINI_STRIP_SIMULATOR_ARCHITECTURE',
Just like is done for `artifactoryUser` and `artifactoryPassword`

2020-12-08 13:26 UTC, stnslw requested changes

2020-12-08 14:36 UTC, marcin-waligorski-onegini commented on hooks/resolve_dependencies.js
> +    writeToStdOut('.');
It adds a `.` to output which in result seems like a progress update :D `Resolving Onegini iOS SDK dependencies.......` :D

2020-12-10 15:29 UTC, stnslw requested changes

2020-12-10 15:29 UTC, stnslw commented on hooks/resolve_dependencies.js
> +      const result = item.match(/stripSimulatorArchitectures=(.*)/i)
Would be nice to handle the scenarios when there is no match. Now it fails with an error: `TypeError: Cannot read property 'length' of null`

2020-12-11 08:52 UTC, stnslw approved these changes

2020-12-11 11:52 UTC, mhwildeman approved these changes

2020-12-11 11:54 UTC, merged