CORDOPLUG-453 bump onegini sdk and min sdk version
Onegini/cordova-plugin-onegini pull request #212
Opened 2021-04-26 09:50 UTC by marcin-onegini

2021-05-20 13:16 UTC, lukaszlabunski requested changes

2021-06-04 15:33 UTC, stnslw commented on docs/public/topics/getting-started.md
> +Please note that the plugin requires iOS Deployment Target to be set to at least version 12.0.0.
Its added to the `Add the plugin to your project` chapter, which I think is better to mention its requirements

2021-06-07 09:56 UTC, lukaszlabunski approved these changes

2021-06-09 07:12 UTC, aleknow approved these changes

2021-06-09 07:23 UTC, merged